### ISSUE TITLE
Regarding u_min and u_max

### ISSUE THREAD

**Issue by annuay** [maflcko/SphereDecoding#1]
Could you please explain what the quantities u_min and u_max are? Is it related to the sphere radius? If yes, could you please explain it once?

**Comment by maflcko** [comment]
u_min and u_max give the lower and upper bounds of the lattice. Those are required for non finite lattices, as defined by lets say, QAM.

The radius of the circle (i.e. intersection of the sphere and the layer) is called rho_n.

**Comment by annuay** [comment]
Thank you. I've figured out how to limit the radius as well.
